//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Will.VegetableShop.DataAccess {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Will.VegetableShop.DataAccess.SqlText", typeof(SqlText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 select
        ///    Title
        ///	,Code
        ///	,Kind
        ///	,Is_Base
        ///	,To_Base
        ///	,Description
        ///	,Is_Activity
        ///	,Input_Time
        ///	,Last_Update_Time
        ///from Measure_Unit
        ///where 1=1
        /// 的本地化字符串。
        /// </summary>
        internal static string MeasureUnitGetSql {
            get {
                return ResourceManager.GetString("MeasureUnitGetSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 declare
        ///    @count int;
        ///begin
        ///    select count(*) into @count from Vegetable_Category where Title=@title;
        ///
        ///	@count=isnull(@count,0);
        ///
        ///	if (@count&gt;0)
        ///	begin
        ///	    @errorString=&apos;标题重复。&apos;;
        ///		goto EndOperate;
        ///	end;
        ///
        ///	insert into Vegetable_Category (Category_Id,Title,Description)values(@categoryId,@title,@description);
        ///
        ///	EndOperate:
        ///	    if (@errorString is null)
        ///		begin
        ///		    @errorString=&apos;success&apos;;
        ///		end;
        ///end; 的本地化字符串。
        /// </summary>
        internal static string VegetableCategoryAddSql {
            get {
                return ResourceManager.GetString("VegetableCategoryAddSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 declare
        ///    objectTitle nvarchar2(200);
        ///begin
        ///    select min(Title) into objectTitle from Vegetable_Category where Category_Id=:objectId;
        ///
        ///    --修改数据
        ///    update Vegetable_Category set
        ///        {0}=:newValue
        ///    where Category_Id=:objectId;
        ///
        ///    --其他操作
        ///    {1}
        ///end;
        /// 的本地化字符串。
        /// </summary>
        internal static string VegetableCategoryEditInfoSaveOra {
            get {
                return ResourceManager.GetString("VegetableCategoryEditInfoSaveOra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select
        ///    Category_Id
        ///	,Title
        ///	,Description
        ///	,Is_Activity
        ///	,Input_Time
        ///from Vegetable_Category
        ///where 1=1
        /// 的本地化字符串。
        /// </summary>
        internal static string VegetableCategoryGetSql {
            get {
                return ResourceManager.GetString("VegetableCategoryGetSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 declare
        ///    @count int;
        ///begin
        ///    select count(*) into @count from Vegetable_Info where Category_Id=@categoryId;
        ///
        ///	@count=isnull(@count,0);
        ///
        ///	if (@count&gt;0)
        ///	begin
        ///	    @errorString=&apos;分类已被使用，不能删除。&apos;;
        ///		goto EndOperate;
        ///	end;
        ///
        ///	delete Vegetable_Category where Category_Id=@categoryId;
        ///
        ///	EndOperate:
        ///	    if (@errorString is null)
        ///		begin
        ///		    @errorString=&apos;success&apos;;
        ///		end;
        ///end; 的本地化字符串。
        /// </summary>
        internal static string VegetableCategoryRemoveSql {
            get {
                return ResourceManager.GetString("VegetableCategoryRemoveSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 declare
        ///    @count int;
        ///
        ///	@oldActivity int;
        ///begin
        ///    select min(Is_Activity) into @oldActivity from Vegetable_Category where Category_Id=@categoryId;
        ///
        ///	if (@oldActivity is null)
        ///	begin
        ///	    @errorString=&apos;指定的分类不存在。&apos;+@categoryId;
        ///		goto EndOperate;
        ///	end;
        ///
        ///	if (@oldActivity=1)
        ///	begin
        ///	    --有使用中的菜品时不能禁用
        ///
        ///	    select count(*) into @count from Vegetable_Info where Category_Id=@categoryId and Is_Activity=1;
        ///	end;
        ///
        ///	@count=isnull(@count,0);
        ///
        ///	if (@count&gt;0)
        ///	begin
        ///	    @errorString=&apos;分类已被使用， [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string VegetableCategorySetActivitySql {
            get {
                return ResourceManager.GetString("VegetableCategorySetActivitySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 declare
        ///    @count int;
        ///begin
        ///    select count(*) into @count from Vegetable_Info where Title=@title;
        ///
        ///	@count=isnull(@count,0);
        ///
        ///	if (@count&gt;0)
        ///	begin
        ///	    @errorString=&apos;标题重复。&apos;;
        ///		goto EndOperate;
        ///	end;
        ///
        ///	insert into Vegetable_Info (Vegetable_Id,Category_Id,Title,Profit_Margin,Description)values(@vegetableId,@categoryId,@title,@profitMargin,@description);
        ///
        ///	EndOperate:
        ///	    if (@errorString is null)
        ///		begin
        ///		    @errorString=&apos;success&apos;;
        ///		end;
        ///end; 的本地化字符串。
        /// </summary>
        internal static string VegetableInfoAddSql {
            get {
                return ResourceManager.GetString("VegetableInfoAddSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 declare
        ///    objectTitle nvarchar2(200);
        ///begin
        ///    select min(Title) into objectTitle from Vegetable_Info where Vegetable_Id=:objectId;
        ///
        ///    --修改数据
        ///    update Vegetable_Info set
        ///        {0}=:newValue
        ///    where Vegetable_Id=:objectId;
        ///
        ///    --其他操作
        ///    {1}
        ///end;
        /// 的本地化字符串。
        /// </summary>
        internal static string VegetableInfoEditInfoSaveOra {
            get {
                return ResourceManager.GetString("VegetableInfoEditInfoSaveOra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select
        ///    v.Vegetable_Id
        ///	,v.Title
        ///	,v.Category_Id
        ///	,c.Title as Category_Title
        ///	,v.Profit_Margin
        ///	,v.Is_Activity
        ///	,v.Description
        ///	,v.Input_Time
        ///from Vegetable_Info v
        ///left join Vegetable_Category c on v.Category_Id=c.Category_Id
        ///where 1=1
        /// 的本地化字符串。
        /// </summary>
        internal static string VegetableInfoGetSql {
            get {
                return ResourceManager.GetString("VegetableInfoGetSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 declare
        ///    @count int;
        ///begin
        ///    select count(*) into @count from Vegetable_Stock_Input where Vegetable_Id=@vegetableId;
        ///
        ///	@count=isnull(@count,0);
        ///
        ///	if (@count&gt;0)
        ///	begin
        ///	    @errorString=&apos;有入库记录，不能删除。&apos;;
        ///		goto EndOperate;
        ///	end;
        ///
        ///    select count(*) into @count from Vegetable_Stock_Output where Vegetable_Id=@vegetableId;
        ///
        ///	@count=isnull(@count,0);
        ///
        ///	if (@count&gt;0)
        ///	begin
        ///	    @errorString=&apos;有出库记录，不能删除。&apos;;
        ///		goto EndOperate;
        ///	end;
        ///
        ///	delete Vegetable_Inventory where Vegetable_Id=@vegetabl [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string VegetableInfoRemoveSql {
            get {
                return ResourceManager.GetString("VegetableInfoRemoveSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 declare
        ///    @count int;
        ///
        ///	@oldActivity int;
        ///begin
        ///    select min(Is_Activity) into @oldActivity from Vegetable_Info where Vegetable_Id=@vegetableId;
        ///
        ///	if (@oldActivity is null)
        ///	begin
        ///	    @errorString=&apos;指定的菜品不存在。&apos;+@vegetableId;
        ///		goto EndOperate;
        ///	end;
        ///
        ///	update Vegetable_Info set Is_Activity=1-Is_Activity where Vegetable_Id=@vegetableId;
        ///
        ///	EndOperate:
        ///	    if (@errorString is null)
        ///		begin
        ///		    @errorString=&apos;success&apos;;
        ///		end;
        ///end; 的本地化字符串。
        /// </summary>
        internal static string VegetableInfoSetActivitySql {
            get {
                return ResourceManager.GetString("VegetableInfoSetActivitySql", resourceCulture);
            }
        }
    }
}
